/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ComicsRouteImport } from './routes/comics'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ToysRouteImport } from './routes/toys'
import { Route as ComicsComicIdRouteImport } from './routes/comics_.$comicId'
import { Route as GamesGameIdRouteImport } from './routes/games_.$gameId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ToysToyIdRouteImport } from './routes/toys_.$toyId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsRoute = ComicsRouteImport.update({
  id: '/comics',
  path: '/comics',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysRoute = ToysRouteImport.update({
  id: '/toys',
  path: '/toys',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsComicIdRoute = ComicsComicIdRouteImport.update({
  id: '/comics_/$comicId',
  path: '/comics/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games_/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysToyIdRoute = ToysToyIdRouteImport.update({
  id: '/toys_/$toyId',
  path: '/toys/$toyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/comics': typeof ComicsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/toys': typeof ToysRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/toys/$toyId': typeof ToysToyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/comics': typeof ComicsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/toys': typeof ToysRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/toys/$toyId': typeof ToysToyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/comics': typeof ComicsRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/toys': typeof ToysRoute
  '/comics_/$comicId': typeof ComicsComicIdRoute
  '/games_/$gameId': typeof GamesGameIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/toys_/$toyId': typeof ToysToyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/comics'
    | '/games'
    | '/login'
    | '/signup'
    | '/toys'
    | '/comics/$comicId'
    | '/games/$gameId'
    | '/orders/$orderId'
    | '/toys/$toyId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/comics'
    | '/games'
    | '/login'
    | '/signup'
    | '/toys'
    | '/comics/$comicId'
    | '/games/$gameId'
    | '/orders/$orderId'
    | '/toys/$toyId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/comics'
    | '/games'
    | '/login'
    | '/signup'
    | '/toys'
    | '/comics_/$comicId'
    | '/games_/$gameId'
    | '/orders/$orderId'
    | '/toys_/$toyId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ComicsRoute: typeof ComicsRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ToysRoute: typeof ToysRoute
  ComicsComicIdRoute: typeof ComicsComicIdRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ToysToyIdRoute: typeof ToysToyIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics': {
      id: '/comics'
      path: '/comics'
      fullPath: '/comics'
      preLoaderRoute: typeof ComicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys': {
      id: '/toys'
      path: '/toys'
      fullPath: '/toys'
      preLoaderRoute: typeof ToysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics_/$comicId': {
      id: '/comics_/$comicId'
      path: '/comics/$comicId'
      fullPath: '/comics/$comicId'
      preLoaderRoute: typeof ComicsComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/$gameId': {
      id: '/games_/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys_/$toyId': {
      id: '/toys_/$toyId'
      path: '/toys/$toyId'
      fullPath: '/toys/$toyId'
      preLoaderRoute: typeof ToysToyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ComicsRoute: ComicsRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ToysRoute: ToysRoute,
  ComicsComicIdRoute: ComicsComicIdRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ToysToyIdRoute: ToysToyIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
