/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ComicsRouteImport } from './routes/comics'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ToysRouteImport } from './routes/toys'
import { Route as ComicsComicIdRouteImport } from './routes/comics_.$comicId'
import { Route as GamesGameIdRouteImport } from './routes/games_.$gameId'
import { Route as ToysToyIdRouteImport } from './routes/toys_.$toyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsRoute = ComicsRouteImport.update({
  id: '/comics',
  path: '/comics',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysRoute = ToysRouteImport.update({
  id: '/toys',
  path: '/toys',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsComicIdRoute = ComicsComicIdRouteImport.update({
  id: '/comics_/$comicId',
  path: '/comics/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games_/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysToyIdRoute = ToysToyIdRouteImport.update({
  id: '/toys_/$toyId',
  path: '/toys/$toyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/comics': typeof ComicsRoute
  '/games': typeof GamesRoute
  '/toys': typeof ToysRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/toys/$toyId': typeof ToysToyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/comics': typeof ComicsRoute
  '/games': typeof GamesRoute
  '/toys': typeof ToysRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/toys/$toyId': typeof ToysToyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/comics': typeof ComicsRoute
  '/games': typeof GamesRoute
  '/toys': typeof ToysRoute
  '/comics_/$comicId': typeof ComicsComicIdRoute
  '/games_/$gameId': typeof GamesGameIdRoute
  '/toys_/$toyId': typeof ToysToyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/comics'
    | '/games'
    | '/toys'
    | '/comics/$comicId'
    | '/games/$gameId'
    | '/toys/$toyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/comics'
    | '/games'
    | '/toys'
    | '/comics/$comicId'
    | '/games/$gameId'
    | '/toys/$toyId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/comics'
    | '/games'
    | '/toys'
    | '/comics_/$comicId'
    | '/games_/$gameId'
    | '/toys_/$toyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ComicsRoute: typeof ComicsRoute
  GamesRoute: typeof GamesRoute
  ToysRoute: typeof ToysRoute
  ComicsComicIdRoute: typeof ComicsComicIdRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  ToysToyIdRoute: typeof ToysToyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics': {
      id: '/comics'
      path: '/comics'
      fullPath: '/comics'
      preLoaderRoute: typeof ComicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys': {
      id: '/toys'
      path: '/toys'
      fullPath: '/toys'
      preLoaderRoute: typeof ToysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics_/$comicId': {
      id: '/comics_/$comicId'
      path: '/comics/$comicId'
      fullPath: '/comics/$comicId'
      preLoaderRoute: typeof ComicsComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/$gameId': {
      id: '/games_/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys_/$toyId': {
      id: '/toys_/$toyId'
      path: '/toys/$toyId'
      fullPath: '/toys/$toyId'
      preLoaderRoute: typeof ToysToyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ComicsRoute: ComicsRoute,
  GamesRoute: GamesRoute,
  ToysRoute: ToysRoute,
  ComicsComicIdRoute: ComicsComicIdRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  ToysToyIdRoute: ToysToyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
